# Generated by Django 4.1.7 on 2023-02-25 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, unique=True)),
                ('ticker', models.CharField(max_length=50, null=True, unique=True)),
                ('volume', models.FloatField(default=0.0)),
                ('current_price', models.FloatField()),
                ('last_price', models.FloatField(default=0.0)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('change', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('date_archived', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserShareWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_price', models.FloatField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('is_watched', models.BooleanField(default=True)),
                ('date_removed', models.DateField(blank=True, null=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.sharesmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSharesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.FloatField(default=0.0)),
                ('quantity_bought', models.PositiveIntegerField(blank=True, null=True)),
                ('date_bought', models.DateField(blank=True, null=True)),
                ('quantity_sold', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('selling_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('selling_date', models.DateField(blank=True, null=True)),
                ('total_purchase', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_sale', models.FloatField(blank=True, default=0.0, null=True)),
                ('margin', models.FloatField(blank=True, default=0.0, null=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.sharesmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
