# Generated by Django 4.1.7 on 2023-02-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersharewatchlist',
            name='watched_price',
            field=models.FloatField(default=0),
        ),
    ]
