# Generated by Django 4.1.7 on 2023-02-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_usersharewatchlist_watched_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersharesmaster',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
