# Generated by Django 4.1.7 on 2023-02-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_usersharesmaster_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersharesmaster',
            old_name='quantity',
            new_name='initial_quantity',
        ),
        migrations.AddField(
            model_name='usersharesmaster',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
