# Generated by Django 4.1.7 on 2023-02-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_rename_quantity_usersharesmaster_initial_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersharesmaster',
            name='initial_quantity',
        ),
    ]
