# Generated by Django 4.1.7 on 2023-02-23 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677157736),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d492376-5597-4b7e-900d-300e77245c12'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
