# Generated by Django 4.1.7 on 2023-02-23 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677174123),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7dae822-1f43-4aec-9bb5-c93f538d3dbf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
