# Generated by Django 4.1.7 on 2023-02-23 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677184443),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0065624-a337-40fc-b210-cb8c6a66899a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
