# Generated by Django 4.1.7 on 2023-02-23 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677185022),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fbd49e0a-a1c0-4732-be77-1eec5a18d7d0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
