# Generated by Django 4.1.7 on 2023-02-23 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677185485),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa6430f0-56c0-487f-8884-524f186c5de9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
