# Generated by Django 4.1.7 on 2023-02-23 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677185552),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5a84313-fea4-400f-aa26-7d0b2d48e0b7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
