# Generated by Django 4.1.7 on 2023-02-24 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677241863),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d28aa9fb-f046-4fa4-86d6-be576959b940'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
