# Generated by Django 4.1.7 on 2023-02-24 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677241885),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90c66495-30b0-4c2f-8763-74a9308023f7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
