# Generated by Django 4.1.7 on 2023-02-24 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677244194),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63bb330c-b32a-4b52-9db3-8f837abea920'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
