# Generated by Django 4.1.7 on 2023-02-24 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677245526),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76c6d72a-4bf1-4cbc-9d07-2e614f39fa1d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
