# Generated by Django 4.1.7 on 2023-02-25 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677326658),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44a450ac-f400-49c8-a0c5-ae7ce3d69d3d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
