# Generated by Django 4.1.7 on 2023-02-25 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677338804),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a0a0070-cc28-4635-9001-6caa6b8e9414'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
