# Generated by Django 4.1.7 on 2023-02-25 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677340124),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('266d10a4-b76a-4b56-b15f-66613c3703f1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
