# Generated by Django 4.1.7 on 2023-02-25 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677340284),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ffb34309-f65a-413d-bcd0-25fee6c80593'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
