# Generated by Django 4.1.7 on 2023-02-25 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677347651),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f15c895-5efa-44f2-8432-67a8607d304a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
