# Generated by Django 4.1.7 on 2023-02-25 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677353678),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5cf031e2-c09f-4d3c-b0f8-17de60d0f84c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
