# Generated by Django 4.1.7 on 2023-02-25 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677355519),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf0f29d3-8e67-451c-b3b9-21801bbd0097'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
