# Generated by Django 4.1.7 on 2023-02-26 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677395567),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8803261e-bbdc-488a-b9cd-cebc8f9ce1a3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
