# Generated by Django 4.1.7 on 2023-02-26 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677396022),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9135e42-0a32-40a2-a651-9b12b81ae266'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
