# Generated by Django 4.1.7 on 2023-02-27 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677465704),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98d3fb75-0164-4e49-8f04-c48171fc4bfd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
