# Generated by Django 4.1.7 on 2023-02-27 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1677466922),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5827f42f-75f5-44fa-9e36-ad00ce4ebf2d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
