# Generated by Django 4.1.7 on 2023-03-05 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1678020398),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14bac828-74fc-4afb-b6a3-bf5368cb74a8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
