# Generated by Django 4.1.7 on 2023-03-05 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_alter_confirmationmodel_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='expire_at',
            field=models.IntegerField(default=1678024944),
        ),
        migrations.AlterField(
            model_name='confirmationmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7a6a218-ed63-422d-92b4-055cbfa75384'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
